server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_DATABASE:thirty_day_challenge}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update

app:
  time-zone: Asia/Seoul